### ISSUE TITLE
error , not able to start active-admin

### ISSUE THREAD

**Issue by thanizebra** [getgauge/gauge-example-ruby#6]
dev@ubuntu-16.04 :~ java -jar activeadmin-demo.war 
2017-03-12 04:15:44.225:INFO::main: Logging initialized @227ms
2017-03-12 04:15:44.231:INFO:oejr.Runner:main: Runner
2017-03-12 04:15:44.342:INFO:oejs.Server:main: jetty-9.2.9.v20150224
2017-03-12 04:15:51.708:WARN:oeja.AnnotationConfiguration:main: ServletContainerInitializers: detected. Class hierarchy: empty
2017-03-12 04:15:52.124:INFO:/:main: INFO: jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.66-b17 on 1.8.0_66-b17 +jit [linux-x86_64]
2017-03-12 04:15:52.125:INFO:/:main: INFO: using a shared (threadsafe!) runtime
git://github.com/activeadmin/activeadmin.git (at master@74799b8) is not yet checked out. Run `bundle install` first.
2017-03-12 04:15:56.751:INFO:/:main: An exception happened during JRuby-Rack startup|exit|--- System|jruby 9.1.7.0 (2.3.1) 2017-01-11 68056ae Java HotSpot(TM) 64-Bit Server VM 25.66-b17 on 1.8.0_66-b17 +jit [linux-x86_64]|Time: 2017-03-12 04:15:56 +0530|Server: jetty/9.2.9.v20150224|jruby.home: uri:classloader://META-INF/jruby.home||--- Context Init Parameters:|jruby.max.runtimes = 1|jruby.min.runtimes = 1|public.root = /|rails.env = production||--- Backtrace|SystemExit: exit|     exit at org/jruby/RubyKernel.java:717|     exit at org/jruby/RubyKernel.java:680|   <main> at /home/dev/.rvm/gems/ruby-2.3.1@gauge-example/gems/bundler-1.14.6/lib/bundler/setup.rb:17|  require at org/jruby/RubyKernel.java:961|  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55|   <main> at /tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF/config/boot.rb:1|  require at org/jruby/RubyKernel.java:961|  require at uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55|   (root) at /tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF/config/boot.rb:4|   (root) at uri:classloader:/jruby/rack/rails/environment3.rb:1|   <main> at uri:classloader:/jruby/rack/rails/environment3.rb:23||--- RubyGems|Gem.dir: /home/dev/.rvm/gems/ruby-2.3.1@gauge-example|Gem.path:|/tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF/gems|/home/dev/.rvm/gems/ruby-2.3.1@gauge-example|/home/dev/.rvm/gems/ruby-2.3.1@global|Activated gems:|  did_you_mean-1.0.1|  bundler-1.14.6||--- Bundler|Bundler.bundle_path: /home/dev/.rvm/gems/ruby-2.3.1@gauge-example|Bundler.root: /tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF|Gemfile: /tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF/Gemfile|Settings:|  gemfile = /tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF/Gemfile|  without = development:test:assets||--- JRuby-Rack Config|compat_version = |default_logger = org.jruby.rack.logging.StandardOutLogger@7bb4ed71|equals = <error: >|err = java.io.PrintStream@40f1aa95|filter_adds_html = true|filter_verifies_resource = false|ignore_environment = false|initial_memory_buffer_size = |initial_runtimes = 1|jms_connection_factory = |jms_jndi_properties = |logger = org.jruby.rack.logging.ServletContextLogger@14be750c|logger_class_name = servlet_context|logger_name = jruby.rack|maximum_memory_buffer_size = |maximum_runtimes = 1|num_initializer_threads = |out = java.io.PrintStream@15e08615|rackup = |rackup_path = |rewindable = true|runtime_arguments = |runtime_environment = |runtime_timeout_seconds = |serial_initialization = false|servlet_context = ServletContext@o.e.j.w.WebAppContext@532760d8{/,file:/tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/,STARTING}{file:/home/dev/github.com/getgauge/gauge-example-ruby/activeadmin-demo.war}|throw_init_exception = false|
2017-03-12 04:15:56.752:WARN:/:main: ERROR: initialization failed
org.jruby.rack.RackInitializationException: exit|?from org/jruby/RubyKernel.java:717:in `exit'|?from org/jruby/RubyKernel.java:680:in `exit'|?from /home/dev/.rvm/gems/ruby-2.3.1@gauge-example/gems/bundler-1.14.6/lib/bundler/setup.rb:17:in `<main>'|?from org/jruby/RubyKernel.java:961:in `require'|?from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require'|?from /tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF/config/boot.rb:1:in `<main>'|?from org/jruby/RubyKernel.java:961:in `require'|?from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require'|?from /tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF/config/boot.rb:4:in `(root)'|?from uri:classloader:/jruby/rack/rails/environment3.rb:1:in `(root)'|?from uri:classloader:/jruby/rack/rails/environment3.rb:23:in `<main>'|
	at org.jruby.rack.RackInitializationException.wrap(RackInitializationException.java:29)
	at org.jruby.rack.RackApplicationFactoryDecorator.init(RackApplicationFactoryDecorator.java:104)
	at org.jruby.rack.RackServletContextListener.contextInitialized(RackServletContextListener.java:50)
	at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:800)
	at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:444)
	at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:791)
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:294)
	at org.eclipse.jetty.webapp.WebAppContext.startWebapp(WebAppContext.java:1349)
	at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1342)
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:505)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.doStart(ContextHandlerCollection.java:163)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
	at org.eclipse.jetty.server.Server.start(Server.java:387)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:61)
	at org.eclipse.jetty.server.Server.doStart(Server.java:354)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:509)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:557)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at WarMain.launchWebServer(WarMain.java:187)
	at WarMain.start(WarMain.java:345)
	at JarMain.doStart(JarMain.java:233)
	at WarMain.main(WarMain.java:367)
Caused by: 
org.jruby.exceptions.RaiseException: (SystemExit) exit
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:717)
	at org.jruby.RubyKernel.exit(org/jruby/RubyKernel.java:680)
	at RUBY.<main>(/home/dev/.rvm/gems/ruby-2.3.1@gauge-example/gems/bundler-1.14.6/lib/bundler/setup.rb:17)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
	at RUBY.<main>(/tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF/config/boot.rb:1)
	at org.jruby.RubyKernel.require(org/jruby/RubyKernel.java:961)
	at uri_3a_classloader_3a_.META_minus_INF.jruby_dot_home.lib.ruby.stdlib.rubygems.core_ext.kernel_require.require(uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55)
	at RUBY.(root)(/tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF/config/boot.rb:4)
	at RUBY.(root)(uri:classloader:/jruby/rack/rails/environment3.rb:1)
	at RUBY.<main>(uri:classloader:/jruby/rack/rails/environment3.rb:23)
2017-03-12 04:15:56.776:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@532760d8{/,file:/tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/,AVAILABLE}{file:/home/dev/github.com/getgauge/gauge-example-ruby/activeadmin-demo.war}
2017-03-12 04:15:56.776:WARN:oejsh.RequestLogHandler:main: !RequestLog
2017-03-12 04:15:56.786:INFO:oejs.ServerConnector:main: Started ServerConnector@2712e8f4{HTTP/1.1}{0.0.0.0:8080}
2017-03-12 04:15:56.787:INFO:oejs.Server:main: Started @12790ms
2017-03-12 04:17:03.295:INFO:/:qtp1721931908-18: DEBUG: due a previous initialization failure application instance can not be returned
2017-03-12 04:17:03.295:INFO:/:qtp1721931908-18: DEBUG: resetting rack response due exception
Ignoring executable-hooks-1.3.2 because its extensions are not built.  Try: gem pristine executable-hooks --version 1.3.2
Ignoring ffi-1.9.14 because its extensions are not built.  Try: gem pristine ffi --version 1.9.14
Ignoring gem-wrappers-1.2.7 because its extensions are not built.  Try: gem pristine gem-wrappers --version 1.2.7
Ignoring nokogiri-1.6.8.1 because its extensions are not built.  Try: gem pristine nokogiri --version 1.6.8.1
^CERROR: java.lang.NullPointerException
2017-03-12 04:19:13.142:INFO:oejs.ServerConnector:Thread-1: Stopped ServerConnector@2712e8f4{HTTP/1.1}{0.0.0.0:8080}
2017-03-12 04:19:13.158:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.w.WebAppContext@532760d8{/,file:/tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/,UNAVAILABLE}{file:/home/dev/github.com/getgauge/gauge-example-ruby/activeadmin-demo.war}
dev@dvh:~/github.com/getgauge/gauge-example-ruby$ java -war activeadmin-demo.war 
Unrecognized option: -war
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.

browser error is 
Internal Server Error (500)
Request Method:	GET
Request URL:	http://localhost:8080/
exit from org/jruby/RubyKernel.java:717:in `exit' from org/jruby/RubyKernel.java:680:in `exit' from /home/dev/.rvm/gems/ruby-2.3.1@gauge-example/gems/bundler-1.14.6/lib/bundler/setup.rb:17:in `<main>' from org/jruby/RubyKernel.java:961:in `require' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require' from /tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF/config/boot.rb:1:in `<main>' from org/jruby/RubyKernel.java:961:in `require' from uri:classloader:/META-INF/jruby.home/lib/ruby/stdlib/rubygems/core_ext/kernel_require.rb:55:in `require' from /tmp/jetty-0.0.0.0-8080-activeadmin-demo.war-_-any-5334367266321891295.dir/webapp/WEB-INF/config/boot.rb:4:in `(root)' from uri:classloader:/jruby/rack/rails/environment3.rb:1:in `(root)' from uri:classloader:/jruby/rack/rails/environment3.rb:23:in `<main>'
You're seeing this error because you use JRuby::Rack::ErrorApp::ShowStatus.

**Comment by joost** [comment]
+1 got the same thing. Not able to start the SUT.

**Comment by Apoorva-GA** [comment]
Hi,
I have rebuild the war. Could you try to start the STU now?

**Comment by joost** [comment]
@Apoorva-GA works for me. Thanks!

**Comment by Apoorva-GA** [comment]
Closing the issue, let me know if you face any issue.
